apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-echo-headers
  namespace: argocd-local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-nginx-headers
  project: default
  source:
    path: charts/nginx-echo-headers
    repoURL: https://github.com/thebrianlopez/charts
    targetRevision: nginx-echo-header
    helm:
      version: v3
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
