apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Values.metadata.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd-local
  project: {{ .Values.spec.project }}
  source:
    path: charts/argo-cd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: dev
    helm:
      version: v3
      valueFiles:
        - {{ .Values.spec.source.helm.valueFiles }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
