apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-kind
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd-local
  project: {{ .Values.spec.project }}
  source:
    path: apps/kind-kind
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
