apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data
  namespace: {{ .Values.metadata.namespace }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Test

  # This list restrics which repos can supply manifests to deploy
  sourceRepos:
  - 'https://github.com/thebrianlopez/charts.git'

  # This list restricts which namespaces and clusters the project can deploy to
  destinations:
  - namespace: data
    server: {{ .Values.spec.destination.server }}

  # Cluster-scoped resources are managed with an allow list
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  # Namespace-scoped resources can be added to the block list
  # namespaceResourceBlacklist:
  # - group: ''
  #   kind: ResourceQuota
  # - group: ''
  #   kind: LimitRange
  # - group: ''
  #   kind: NetworkPolicy

  # Namespace-scoped resources can also be added to an allow list
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  # We're going to manage RBAC globally, but you can find project-specific details here:
  # https://argoproj.github.io/argo-cd/user-guide/projects/#configuring-rbac-with-projects
  roles: []
  # A role which provides read-only access to all applications in the project
  # - name: read-only
  #   description: Read-only privileges to my-project
  #   policies:
  #   - p, proj:my-project:read-only, applications, get, my-project/*, allow
  #   groups:
  #   - my-oidc-group

  # # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  # # sync privileges to a CI system
  # - name: ci-role
  #   description: Sync privileges for guestbook-dev
  #   policies:
  #   - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow

  #   # NOTE: JWT tokens can only be generated by the API server and the token is not persisted
  #   # anywhere by Argo CD. It can be prematurely revoked by removing the entry from this list.
  #   jwtTokens:
  #   - iat: 1535390316
